#ifndef _DISPLAY_H
#define _DISPLAY_H

#include "configure.h"

#define NOTIFY_DIS_CHANGE
#define DISPLAY_SHINE_BIT	true	//定义要点亮显示应该设置显示缓存的值为1还是0
#define TOTAL_SEG 			16	//可用数字显示位
#define DISPLAY_MEMORY_SIZE	16	//显示缓存字节
//#define DISPLAY_TEST//测试显示
//#define DISPLAY_GLINT_POINT //使用点闪烁
//extern uint8 DisplayDeviceMemImage[DISPLAY_MEMORY_SIZE];		//显示缓存
extern uint8 perchdata dislinebuf[DIS_LINEBUF_SIZE];//字符操作缓存
#ifdef NOTIFY_DIS_CHANGE
extern bool DisplayChanged;
#endif//NOTIFY_DIS_CHANGE


void IniDisplay();							//初始化将清空缓存
void UpdateDisplay();
void ShowString(char const*s,uint8 stp,uint8 len);//s：字符串
void ShowUint8(uint8 lc,uint8 dat);
void SetdislinebufTo(char c);
//extern uint8 GlintLen;
extern bool GlintEn;
extern uint8 GlintLc;
extern uint8 GlintData;
void SetGlint();
#define StopGlint() (GlintEn=0)
//#define StopGlint() (GlintLen=0)
extern void PollingDisplay500ms();
#ifdef DISPLAY_GLINT_POINT
extern bool DisplayGlintState;
extern uint8 DisplayGlintPoint;
extern bool DisplayGlintExitState;
extern void ExitDisplayGlintPoint();
extern void SetDisplayGlintPoint(uint8 Point,bool ExitState);

#endif//DISPLAY_GLINT_POINT

#ifdef DISPLAY_TEST
extern void DisplayTestNext(bool v);//v:方向
#endif//DISPLAY_TEST


//extern void RefurbishDisplay();						//写显示缓存到显示设备	

/*
** Definition for 7-seg display
**
** we assume 7-seg are defined as traditional 7-segment LED.
**
**	 AAAA			
**	C    B				 
**	C    B				 
**	 DDDD				 
**	F    E				 
**	F    E				 
**	 GGGG				 
**					 
**					 

*/


#if 0//默认
#define	VFD_7SEG_SA	(0x01)
#define	VFD_7SEG_SB	(0x02)
#define	VFD_7SEG_SC	(0x04)
#define	VFD_7SEG_SD	(0x08)
#define	VFD_7SEG_SE	(0x10)
#define	VFD_7SEG_SF	(0x20)
#define	VFD_7SEG_SG	(0x40)
#endif

#define	VFD_7SEG_SA	(1<<2)
#define	VFD_7SEG_SB	(1<<0)
#define	VFD_7SEG_SC	(1<<1)
#define	VFD_7SEG_SD	(1<<3)
#define	VFD_7SEG_SE	(1<<4)
#define	VFD_7SEG_SF	(1<<6)
#define	VFD_7SEG_SG	(1<<7)

#define	VFD_7SEG_0	(VFD_7SEG_SA|VFD_7SEG_SB|VFD_7SEG_SG|VFD_7SEG_SC|VFD_7SEG_SE|VFD_7SEG_SF)
#define	VFD_7SEG_1	(VFD_7SEG_SB|VFD_7SEG_SE)
#define	VFD_7SEG_2	(VFD_7SEG_SA|VFD_7SEG_SB|VFD_7SEG_SD|VFD_7SEG_SF|VFD_7SEG_SG)
#define	VFD_7SEG_3	(VFD_7SEG_SA|VFD_7SEG_SB|VFD_7SEG_SD|VFD_7SEG_SE|VFD_7SEG_SG)
#define	VFD_7SEG_4	(VFD_7SEG_SC|VFD_7SEG_SD|VFD_7SEG_SB|VFD_7SEG_SE)
#define	VFD_7SEG_5	(VFD_7SEG_SA|VFD_7SEG_SC|VFD_7SEG_SD|VFD_7SEG_SE|VFD_7SEG_SG)
#define	VFD_7SEG_6	(VFD_7SEG_SA|VFD_7SEG_SC|VFD_7SEG_SD|VFD_7SEG_SF|VFD_7SEG_SE|VFD_7SEG_SG)
#define	VFD_7SEG_7	(VFD_7SEG_SA|VFD_7SEG_SB|VFD_7SEG_SE)
#define	VFD_7SEG_8	(VFD_7SEG_SA|VFD_7SEG_SB|VFD_7SEG_SC|VFD_7SEG_SD|VFD_7SEG_SE|VFD_7SEG_SF|VFD_7SEG_SG)
#define	VFD_7SEG_9	(VFD_7SEG_SA|VFD_7SEG_SB|VFD_7SEG_SC|VFD_7SEG_SD|VFD_7SEG_SE|VFD_7SEG_SG)
#define	VFD_7SEG_DIG_MASK	(VFD_7SEG_8)

#define	VFD_7SEG_A	(VFD_7SEG_SA|VFD_7SEG_SB|VFD_7SEG_SC|VFD_7SEG_SE|VFD_7SEG_SF|VFD_7SEG_SD)
#define	VFD_7SEG_b	(VFD_7SEG_SC|VFD_7SEG_SD|VFD_7SEG_SE|VFD_7SEG_SF|VFD_7SEG_SG)
#define	VFD_7SEG_B	VFD_7SEG_b
#define	VFD_7SEG_C	(VFD_7SEG_SA|VFD_7SEG_SC|VFD_7SEG_SF|VFD_7SEG_SG)
#define	VFD_7SEG_d	(VFD_7SEG_SB|VFD_7SEG_SD|VFD_7SEG_SE|VFD_7SEG_SF|VFD_7SEG_SG)
#define	VFD_7SEG_D	VFD_7SEG_d
#define	VFD_7SEG_E	(VFD_7SEG_SA|VFD_7SEG_SC|VFD_7SEG_SD|VFD_7SEG_SF|VFD_7SEG_SG)
#define	VFD_7SEG_F	(VFD_7SEG_SA|VFD_7SEG_SC|VFD_7SEG_SD|VFD_7SEG_SF)
#define	VFD_7SEG_G	(VFD_7SEG_SA|VFD_7SEG_SB|VFD_7SEG_SC|VFD_7SEG_SD|VFD_7SEG_SE|VFD_7SEG_SG)
#define	VFD_7SEG_H	(VFD_7SEG_SB|VFD_7SEG_SC|VFD_7SEG_SD|VFD_7SEG_SF|VFD_7SEG_SE)
#define	VFD_7SEG_I	(VFD_7SEG_SB|VFD_7SEG_SE)
#define	VFD_7SEG_J	(VFD_7SEG_SB|VFD_7SEG_SE|VFD_7SEG_SG|VFD_7SEG_SF)
#define	VFD_7SEG_K	(VFD_7SEG_SB|VFD_7SEG_SE|VFD_7SEG_SG|VFD_7SEG_SF)
#define	VFD_7SEG_L	(VFD_7SEG_SC|VFD_7SEG_SF|VFD_7SEG_SG)
#define	VFD_7SEG_M	(VFD_7SEG_SF|VFD_7SEG_SD|VFD_7SEG_SE)
#define	VFD_7SEG_N	(VFD_7SEG_SA|VFD_7SEG_SB|VFD_7SEG_SC|VFD_7SEG_SE|VFD_7SEG_SF)
//#define	VFD_7SEG_N	(VFD_7SEG_SF|VFD_7SEG_SD|VFD_7SEG_SE)
#define	VFD_7SEG_O	(VFD_7SEG_SA|VFD_7SEG_SB|VFD_7SEG_SG|VFD_7SEG_SC|VFD_7SEG_SE|VFD_7SEG_SF)
#define	VFD_7SEG_P	(VFD_7SEG_SA|VFD_7SEG_SB|VFD_7SEG_SC|VFD_7SEG_SD|VFD_7SEG_SF)
#define	VFD_7SEG_Q	(VFD_7SEG_SA|VFD_7SEG_SB|VFD_7SEG_SC|VFD_7SEG_SD|VFD_7SEG_SF)
#define	VFD_7SEG_r	(VFD_7SEG_SD|VFD_7SEG_SF)
#define	VFD_7SEG_R	VFD_7SEG_r
#define	VFD_7SEG_S	(VFD_7SEG_SA|VFD_7SEG_SC|VFD_7SEG_SD|VFD_7SEG_SE|VFD_7SEG_SG)
#define	VFD_7SEG_t	(VFD_7SEG_SC|VFD_7SEG_SD|VFD_7SEG_SF|VFD_7SEG_SG)
#define	VFD_7SEG_T	VFD_7SEG_t
#define	VFD_7SEG_U	(VFD_7SEG_SC|VFD_7SEG_SB|VFD_7SEG_SF|VFD_7SEG_SE|VFD_7SEG_SG)
#define	VFD_7SEG_V	(VFD_7SEG_SC|VFD_7SEG_SB|VFD_7SEG_SF|VFD_7SEG_SE|VFD_7SEG_SG)
#define	VFD_7SEG_W	(VFD_7SEG_SC|VFD_7SEG_SB|VFD_7SEG_SF|VFD_7SEG_SE|VFD_7SEG_SG)
#define	VFD_7SEG_X	(VFD_7SEG_SC|VFD_7SEG_SB|VFD_7SEG_SF|VFD_7SEG_SE|VFD_7SEG_SG)
#define	VFD_7SEG_Y	(VFD_7SEG_SC|VFD_7SEG_SD|VFD_7SEG_SB|VFD_7SEG_SE|VFD_7SEG_SG)
#define	VFD_7SEG_Z	(VFD_7SEG_SA|VFD_7SEG_SB|VFD_7SEG_SD|VFD_7SEG_SF|VFD_7SEG_SG)


#define	VFD_7SEG__  (VFD_7SEG_SG)//_
#define	VFD_7SEG___  (VFD_7SEG_SD)//-
#define VFD_7SEG_MASK  0xff
#if 1//2
#define	VFD2_7SEG_SA	(1<<6)
#define	VFD2_7SEG_SB	(1<<4)
#define	VFD2_7SEG_SC	(1<<5)
#define	VFD2_7SEG_SD	(1<<0)
#define	VFD2_7SEG_SE	(1<<1)
#define	VFD2_7SEG_SF	(1<<7)
#define	VFD2_7SEG_SG	(1<<3)

#define	VFD2_7SEG_0	(VFD2_7SEG_SA|VFD2_7SEG_SB|VFD2_7SEG_SG|VFD2_7SEG_SC|VFD2_7SEG_SE|VFD2_7SEG_SF)
#define	VFD2_7SEG_1	(VFD2_7SEG_SB|VFD2_7SEG_SE)
#define	VFD2_7SEG_2	(VFD2_7SEG_SA|VFD2_7SEG_SB|VFD2_7SEG_SD|VFD2_7SEG_SF|VFD2_7SEG_SG)
#define	VFD2_7SEG_3	(VFD2_7SEG_SA|VFD2_7SEG_SB|VFD2_7SEG_SD|VFD2_7SEG_SE|VFD2_7SEG_SG)
#define	VFD2_7SEG_4	(VFD2_7SEG_SC|VFD2_7SEG_SD|VFD2_7SEG_SB|VFD2_7SEG_SE)
#define	VFD2_7SEG_5	(VFD2_7SEG_SA|VFD2_7SEG_SC|VFD2_7SEG_SD|VFD2_7SEG_SE|VFD2_7SEG_SG)
#define	VFD2_7SEG_6	(VFD2_7SEG_SA|VFD2_7SEG_SC|VFD2_7SEG_SD|VFD2_7SEG_SF|VFD2_7SEG_SE|VFD2_7SEG_SG)
#define	VFD2_7SEG_7	(VFD2_7SEG_SA|VFD2_7SEG_SB|VFD2_7SEG_SE)
#define	VFD2_7SEG_8	(VFD2_7SEG_SA|VFD2_7SEG_SB|VFD2_7SEG_SC|VFD2_7SEG_SD|VFD2_7SEG_SE|VFD2_7SEG_SF|VFD2_7SEG_SG)
#define	VFD2_7SEG_9	(VFD2_7SEG_SA|VFD2_7SEG_SB|VFD2_7SEG_SC|VFD2_7SEG_SD|VFD2_7SEG_SE|VFD2_7SEG_SG)
#define	VFD2_7SEG_DIG_MASK	(VFD2_7SEG_8)
		   
#define	VFD2_7SEG_A	(VFD2_7SEG_SA|VFD2_7SEG_SB|VFD2_7SEG_SC|VFD2_7SEG_SE|VFD2_7SEG_SF|VFD2_7SEG_SD)
#define	VFD2_7SEG_b	(VFD2_7SEG_SC|VFD2_7SEG_SD|VFD2_7SEG_SE|VFD2_7SEG_SF|VFD2_7SEG_SG)
#define	VFD2_7SEG_B	VFD2_7SEG_b
#define	VFD2_7SEG_C	(VFD2_7SEG_SA|VFD2_7SEG_SC|VFD2_7SEG_SF|VFD2_7SEG_SG)
#define	VFD2_7SEG_d	(VFD2_7SEG_SB|VFD2_7SEG_SD|VFD2_7SEG_SE|VFD2_7SEG_SF|VFD2_7SEG_SG)
#define	VFD2_7SEG_D	VFD2_7SEG_d
#define	VFD2_7SEG_E	(VFD2_7SEG_SA|VFD2_7SEG_SC|VFD2_7SEG_SD|VFD2_7SEG_SF|VFD2_7SEG_SG)
#define	VFD2_7SEG_F	(VFD2_7SEG_SA|VFD2_7SEG_SC|VFD2_7SEG_SD|VFD2_7SEG_SF)
#define	VFD2_7SEG_G	(VFD2_7SEG_SA|VFD2_7SEG_SB|VFD2_7SEG_SC|VFD2_7SEG_SD|VFD2_7SEG_SE|VFD2_7SEG_SG)
#define	VFD2_7SEG_H	(VFD2_7SEG_SB|VFD2_7SEG_SC|VFD2_7SEG_SD|VFD2_7SEG_SF|VFD2_7SEG_SE)
#define	VFD2_7SEG_I	(VFD2_7SEG_SB|VFD2_7SEG_SE)
#define	VFD2_7SEG_J	(VFD2_7SEG_SB|VFD2_7SEG_SE|VFD2_7SEG_SG|VFD2_7SEG_SF)
#define	VFD2_7SEG_K	(VFD2_7SEG_SB|VFD2_7SEG_SE|VFD2_7SEG_SG|VFD2_7SEG_SF)
#define	VFD2_7SEG_L	(VFD2_7SEG_SC|VFD2_7SEG_SF|VFD2_7SEG_SG)
#define	VFD2_7SEG_M	(VFD2_7SEG_SF|VFD2_7SEG_SD|VFD2_7SEG_SE)
#define	VFD2_7SEG_N	(VFD2_7SEG_SA|VFD2_7SEG_SB|VFD2_7SEG_SC|VFD2_7SEG_SE|VFD2_7SEG_SF)
//#defineVFD2_7SEG_N	(VFD2_7SEG_SF|VFD2_7SEG_SD|VFD2_7SEG_SE)
#define	VFD2_7SEG_O	(VFD2_7SEG_SA|VFD2_7SEG_SB|VFD2_7SEG_SG|VFD2_7SEG_SC|VFD2_7SEG_SE|VFD2_7SEG_SF)
#define	VFD2_7SEG_P	(VFD2_7SEG_SA|VFD2_7SEG_SB|VFD2_7SEG_SC|VFD2_7SEG_SD|VFD2_7SEG_SF)
#define	VFD2_7SEG_Q	(VFD2_7SEG_SA|VFD2_7SEG_SB|VFD2_7SEG_SC|VFD2_7SEG_SD|VFD2_7SEG_SF)
#define	VFD2_7SEG_r	(VFD2_7SEG_SD|VFD2_7SEG_SF)
#define	VFD2_7SEG_R	VFD2_7SEG_r
#define	VFD2_7SEG_S	(VFD2_7SEG_SA|VFD2_7SEG_SC|VFD2_7SEG_SD|VFD2_7SEG_SE|VFD2_7SEG_SG)
#define	VFD2_7SEG_t	(VFD2_7SEG_SC|VFD2_7SEG_SD|VFD2_7SEG_SF|VFD2_7SEG_SG)
#define	VFD2_7SEG_T	VFD2_7SEG_t
#define	VFD2_7SEG_U	(VFD2_7SEG_SC|VFD2_7SEG_SB|VFD2_7SEG_SF|VFD2_7SEG_SE|VFD2_7SEG_SG)
#define	VFD2_7SEG_V	(VFD2_7SEG_SC|VFD2_7SEG_SB|VFD2_7SEG_SF|VFD2_7SEG_SE|VFD2_7SEG_SG)
#define	VFD2_7SEG_W	(VFD2_7SEG_SC|VFD2_7SEG_SB|VFD2_7SEG_SF|VFD2_7SEG_SE|VFD2_7SEG_SG)
#define	VFD2_7SEG_X	(VFD2_7SEG_SC|VFD2_7SEG_SB|VFD2_7SEG_SF|VFD2_7SEG_SE|VFD2_7SEG_SG)
#define	VFD2_7SEG_Y	(VFD2_7SEG_SC|VFD2_7SEG_SD|VFD2_7SEG_SB|VFD2_7SEG_SE|VFD2_7SEG_SG)
#define	VFD2_7SEG_Z	(VFD2_7SEG_SA|VFD2_7SEG_SB|VFD2_7SEG_SD|VFD2_7SEG_SF|VFD2_7SEG_SG)


#define	VFD2_7SEG__  (VFD2_7SEG_SG)//_
#define	VFD2_7SEG___  (VFD2_7SEG_SD)//-
#define VFD2_7SEG_MASK  0xff
#endif	   
		   
#endif //_DISPLAY_H		  
		   