#include <avr/interrupt.h>

EMPTY_INTERRUPT(INT0_vect);
EMPTY_INTERRUPT(INT1_vect);
EMPTY_INTERRUPT(TIMER2_COMP_vect);
EMPTY_INTERRUPT(TIMER2_OVF_vect);
EMPTY_INTERRUPT(TIMER1_CAPT_vect);
EMPTY_INTERRUPT(TIMER1_COMPA_vect);
EMPTY_INTERRUPT(TIMER1_COMPB_vect);
EMPTY_INTERRUPT(TIMER1_OVF_vect);
EMPTY_INTERRUPT(TIMER0_OVF_vect);
//EMPTY_INTERRUPT(SPI_STC_vect);
//EMPTY_INTERRUPT(USART_RXC_vect);
//EMPTY_INTERRUPT(USART_UDRE_vect);
//EMPTY_INTERRUPT(USART_TXC_vect);
EMPTY_INTERRUPT(ADC_vect);
EMPTY_INTERRUPT(EE_RDY_vect);
EMPTY_INTERRUPT(ANA_COMP_vect);
EMPTY_INTERRUPT(TWI_vect);
EMPTY_INTERRUPT(TIMER0_COMP_vect);
EMPTY_INTERRUPT(SPM_RDY_vect);
